#uimanager default colour values
#Thu Jan 29 17:21:23 MST 2026
Button.background=0xffeeeeee
Button.darkShadow=0xff7a8a99
Button.disabledText=0xff999999
Button.disabledToolBarBorderBackground=0xffcccccc
Button.focus=0xffa3b8cc
Button.foreground=0xff333333
Button.highlight=0xffffffff
Button.light=0xffffffff
Button.select=0xffb8cfe5
Button.shadow=0xffb8cfe5
Button.toolBarBorderBackground=0xff999999
CheckBox.background=0xffeeeeee
CheckBox.disabledText=0xff999999
CheckBox.focus=0xffa3b8cc
CheckBox.foreground=0xff333333
CheckBoxMenuItem.acceleratorForeground=0xff6382bf
CheckBoxMenuItem.acceleratorSelectionForeground=0xff333333
CheckBoxMenuItem.background=0xffeeeeee
CheckBoxMenuItem.disabledForeground=0xff999999
CheckBoxMenuItem.foreground=0xff333333
CheckBoxMenuItem.selectionBackground=0xffa3b8cc
CheckBoxMenuItem.selectionForeground=0xff333333
Checkbox.select=0xffb8cfe5
ColorChooser.background=0xffeeeeee
ColorChooser.foreground=0xff333333
ColorChooser.swatchesDefaultRecentColor=0xffeeeeee
ComboBox.background=0xffeeeeee
ComboBox.buttonBackground=0xffeeeeee
ComboBox.buttonDarkShadow=0xff7a8a99
ComboBox.buttonHighlight=0xffffffff
ComboBox.buttonShadow=0xffb8cfe5
ComboBox.disabledBackground=0xffeeeeee
ComboBox.disabledForeground=0xffb8cfe5
ComboBox.foreground=0xff333333
ComboBox.selectionBackground=0xffa3b8cc
ComboBox.selectionForeground=0xff333333
Desktop.background=0xffffffff
DesktopIcon.background=0xffeeeeee
DesktopIcon.foreground=0xff333333
EditorPane.background=0xffffffff
EditorPane.caretForeground=0xff333333
EditorPane.foreground=0xff333333
EditorPane.inactiveForeground=0xffb8cfe5
EditorPane.selectionBackground=0xffb8cfe5
EditorPane.selectionForeground=0xff333333
FormattedTextField.background=0xffffffff
FormattedTextField.caretForeground=0xff333333
FormattedTextField.foreground=0xff333333
FormattedTextField.inactiveBackground=0xffeeeeee
FormattedTextField.inactiveForeground=0xffb8cfe5
FormattedTextField.selectionBackground=0xffb8cfe5
FormattedTextField.selectionForeground=0xff333333
InternalFrame.activeTitleBackground=0xffb8cfe5
InternalFrame.activeTitleForeground=0xff333333
InternalFrame.borderColor=0xffeeeeee
InternalFrame.borderDarkShadow=0xff7a8a99
InternalFrame.borderHighlight=0xffffffff
InternalFrame.borderLight=0xffffffff
InternalFrame.borderShadow=0xffb8cfe5
InternalFrame.inactiveTitleBackground=0xffeeeeee
InternalFrame.inactiveTitleForeground=0xff333333
Label.background=0xffeeeeee
Label.disabledForeground=0xff999999
Label.disabledShadow=0xffb8cfe5
Label.foreground=0xff333333
List.background=0xffffffff
List.dropCellBackground=0xffd2e9ff
List.dropLineColor=0xff6382bf
List.foreground=0xff333333
List.selectionBackground=0xffb8cfe5
List.selectionForeground=0xff333333
Menu.acceleratorForeground=0xff6382bf
Menu.acceleratorSelectionForeground=0xff333333
Menu.background=0xffeeeeee
Menu.disabledForeground=0xff999999
Menu.foreground=0xff333333
Menu.selectionBackground=0xffa3b8cc
Menu.selectionForeground=0xff333333
MenuBar.background=0xffeeeeee
MenuBar.borderColor=0xffcccccc
MenuBar.foreground=0xff333333
MenuBar.highlight=0xffffffff
MenuBar.shadow=0xffb8cfe5
MenuItem.acceleratorForeground=0xff6382bf
MenuItem.acceleratorSelectionForeground=0xff333333
MenuItem.background=0xffeeeeee
MenuItem.disabledForeground=0xff999999
MenuItem.foreground=0xff333333
MenuItem.selectionBackground=0xffa3b8cc
MenuItem.selectionForeground=0xff333333
OptionPane.background=0xffeeeeee
OptionPane.errorDialog.border.background=0xff993333
OptionPane.errorDialog.titlePane.background=0xffff9999
OptionPane.errorDialog.titlePane.foreground=0xff330000
OptionPane.errorDialog.titlePane.shadow=0xffcc6666
OptionPane.foreground=0xff333333
OptionPane.messageForeground=0xff333333
OptionPane.questionDialog.border.background=0xff336633
OptionPane.questionDialog.titlePane.background=0xff99cc99
OptionPane.questionDialog.titlePane.foreground=0xff003300
OptionPane.questionDialog.titlePane.shadow=0xff669966
OptionPane.warningDialog.border.background=0xff996633
OptionPane.warningDialog.titlePane.background=0xffffcc99
OptionPane.warningDialog.titlePane.foreground=0xff663300
OptionPane.warningDialog.titlePane.shadow=0xffcc9966
Panel.background=0xffeeeeee
Panel.foreground=0xff333333
PasswordField.background=0xffffffff
PasswordField.caretForeground=0xff333333
PasswordField.foreground=0xff333333
PasswordField.inactiveBackground=0xffeeeeee
PasswordField.inactiveForeground=0xffb8cfe5
PasswordField.selectionBackground=0xffb8cfe5
PasswordField.selectionForeground=0xff333333
PopupMenu.background=0xffeeeeee
PopupMenu.foreground=0xff333333
ProgressBar.background=0xffeeeeee
ProgressBar.foreground=0xffa3b8cc
ProgressBar.selectionBackground=0xff6382bf
ProgressBar.selectionForeground=0xffeeeeee
RadioButton.background=0xffeeeeee
RadioButton.darkShadow=0xff7a8a99
RadioButton.disabledText=0xff999999
RadioButton.focus=0xffa3b8cc
RadioButton.foreground=0xff333333
RadioButton.highlight=0xffffffff
RadioButton.light=0xffffffff
RadioButton.select=0xffb8cfe5
RadioButton.shadow=0xffb8cfe5
RadioButtonMenuItem.acceleratorForeground=0xff6382bf
RadioButtonMenuItem.acceleratorSelectionForeground=0xff333333
RadioButtonMenuItem.background=0xffeeeeee
RadioButtonMenuItem.disabledForeground=0xff999999
RadioButtonMenuItem.foreground=0xff333333
RadioButtonMenuItem.selectionBackground=0xffa3b8cc
RadioButtonMenuItem.selectionForeground=0xff333333
ScrollBar.background=0xffeeeeee
ScrollBar.darkShadow=0xff7a8a99
ScrollBar.foreground=0xffeeeeee
ScrollBar.highlight=0xffffffff
ScrollBar.shadow=0xffb8cfe5
ScrollBar.thumb=0xffa3b8cc
ScrollBar.thumbDarkShadow=0xff7a8a99
ScrollBar.thumbHighlight=0xffb8cfe5
ScrollBar.thumbShadow=0xff6382bf
ScrollBar.track=0xffeeeeee
ScrollBar.trackHighlight=0xff7a8a99
ScrollPane.background=0xffeeeeee
ScrollPane.foreground=0xff333333
Separator.background=0xffffffff
Separator.foreground=0xff6382bf
Separator.highlight=0xffffffff
Separator.shadow=0xffb8cfe5
Slider.altTrackColor=0xffd2e2ef
Slider.background=0xffeeeeee
Slider.focus=0xffa3b8cc
Slider.foreground=0xffa3b8cc
Slider.highlight=0xffffffff
Slider.shadow=0xffb8cfe5
Spinner.background=0xffeeeeee
Spinner.foreground=0xffeeeeee
SplitPane.background=0xffeeeeee
SplitPane.darkShadow=0xff7a8a99
SplitPane.dividerFocusColor=0xffc8ddf2
SplitPane.highlight=0xffffffff
SplitPane.shadow=0xffb8cfe5
SplitPaneDivider.draggingColor=0xff404040
TabbedPane.background=0xffb8cfe5
TabbedPane.borderHightlightColor=0xff6382bf
TabbedPane.contentAreaColor=0xffc8ddf2
TabbedPane.darkShadow=0xff7a8a99
TabbedPane.focus=0xff6382bf
TabbedPane.foreground=0xff333333
TabbedPane.highlight=0xffffffff
TabbedPane.light=0xffeeeeee
TabbedPane.selectHighlight=0xffffffff
TabbedPane.selected=0xffc8ddf2
TabbedPane.shadow=0xffb8cfe5
TabbedPane.tabAreaBackground=0xffdadada
TabbedPane.unselectedBackground=0xffeeeeee
Table.background=0xffffffff
Table.dropCellBackground=0xffd2e9ff
Table.dropLineColor=0xff6382bf
Table.dropLineShortColor=0xff333333
Table.focusCellBackground=0xffffffff
Table.focusCellForeground=0xff333333
Table.foreground=0xff333333
Table.gridColor=0xff7a8a99
Table.selectionBackground=0xffb8cfe5
Table.selectionForeground=0xff333333
Table.sortIconColor=0xffb8cfe5
TableHeader.background=0xffeeeeee
TableHeader.focusCellBackground=0xffc8ddf2
TableHeader.foreground=0xff333333
TextArea.background=0xffffffff
TextArea.caretForeground=0xff333333
TextArea.foreground=0xff333333
TextArea.inactiveForeground=0xffb8cfe5
TextArea.selectionBackground=0xffb8cfe5
TextArea.selectionForeground=0xff333333
TextField.background=0xffffffff
TextField.caretForeground=0xff333333
TextField.darkShadow=0xff7a8a99
TextField.foreground=0xff333333
TextField.highlight=0xffffffff
TextField.inactiveBackground=0xffeeeeee
TextField.inactiveForeground=0xffb8cfe5
TextField.light=0xffffffff
TextField.selectionBackground=0xffb8cfe5
TextField.selectionForeground=0xff333333
TextField.shadow=0xffb8cfe5
TextPane.background=0xffffffff
TextPane.caretForeground=0xff333333
TextPane.foreground=0xff333333
TextPane.inactiveForeground=0xffb8cfe5
TextPane.selectionBackground=0xffb8cfe5
TextPane.selectionForeground=0xff333333
TitledBorder.titleColor=0xff333333
ToggleButton.background=0xffeeeeee
ToggleButton.darkShadow=0xff7a8a99
ToggleButton.disabledText=0xff999999
ToggleButton.focus=0xffa3b8cc
ToggleButton.foreground=0xff333333
ToggleButton.highlight=0xffffffff
ToggleButton.light=0xffffffff
ToggleButton.select=0xffb8cfe5
ToggleButton.shadow=0xffb8cfe5
ToolBar.background=0xffeeeeee
ToolBar.borderColor=0xffcccccc
ToolBar.darkShadow=0xff7a8a99
ToolBar.dockingBackground=0xffeeeeee
ToolBar.dockingForeground=0xff6382bf
ToolBar.floatingBackground=0xffeeeeee
ToolBar.floatingForeground=0xffb8cfe5
ToolBar.foreground=0xff333333
ToolBar.highlight=0xffffffff
ToolBar.light=0xffffffff
ToolBar.shadow=0xffb8cfe5
ToolTip.background=0xffb8cfe5
ToolTip.backgroundInactive=0xffeeeeee
ToolTip.foreground=0xff333333
ToolTip.foregroundInactive=0xff7a8a99
Tree.background=0xffffffff
Tree.dropCellBackground=0xffd2e9ff
Tree.dropLineColor=0xff6382bf
Tree.foreground=0xff333333
Tree.hash=0xffb8cfe5
Tree.line=0xffb8cfe5
Tree.selectionBackground=0xffb8cfe5
Tree.selectionBorderColor=0xff6382bf
Tree.selectionForeground=0xff333333
Tree.textBackground=0xffffffff
Tree.textForeground=0xff333333
Viewport.background=0xffeeeeee
Viewport.foreground=0xff333333
activeCaption=0xffb8cfe5
activeCaptionBorder=0xffa3b8cc
activeCaptionText=0xff333333
control=0xffeeeeee
controlDkShadow=0xff7a8a99
controlHighlight=0xffffffff
controlLtHighlight=0xffffffff
controlShadow=0xffb8cfe5
controlText=0xff333333
desktop=0xffffffff
inactiveCaption=0xffeeeeee
inactiveCaptionBorder=0xffb8cfe5
inactiveCaptionText=0xff333333
info=0xffb8cfe5
infoText=0xff333333
menu=0xffeeeeee
menuText=0xff333333
scrollbar=0xffeeeeee
text=0xffffffff
textHighlight=0xffb8cfe5
textHighlightText=0xff333333
textInactiveText=0xffb8cfe5
textText=0xff333333
window=0xffffffff
windowBorder=0xffeeeeee
windowText=0xff333333
