Name=BasicDark
White=0x5f556a
Black=0xe5ceb4
Primary1=0x45444f
Primary2=0x5f556a
Primary3=0x646365
Secondary1=0x352b42
Secondary2=0x5f556a
Secondary3=0x4b4158
EditorBackground=0x212123
EditorForeground=0xf2f0e5
EditorLineHighlight=0x352b42
EditorSelection=0x646365
EditorCaretColor=0xf2f0e5
EvenRowBackground=0x45444f
EvenRowForeground=0xf2f0e5
OddRowBackground=0x646365
OddRowForeground=0xf2f0e5
TextSegmentHighlightBackground=0xa77b5b
TextSegmentHighlightForeground=0xf2f0e5
TextSegmentDelaySlotHighlightBackground=0x567b79
TextSegmentDelaySlotHighlightForeground=0xf2f0e5
DataSegmentHighlightBackground=0x43436a
DataSegmentHighlightForeground=0xf2f0e5
RegisterHighlightBackground=0x4e584a
RegisterHighlightForeground=0xf2f0e5