# example theme
Name=ExampleTheme

# base colours
White=0xf7ebe9
Black=0x333333
PrimaryDarkShadow=0x5ac5cc
PrimaryShadow=0x6dd5cc
Primary=0xbad5cc
SecondaryDarkShadow=0xe57d88
SecondaryShadow=0xe59f88
Secondary=0xe3d5cc

# text editor
EditorBackground=0x1f0e1c
EditorForeground=0xf5edba
EditorLineHighlight=0x3e2137
EditorSelection=0xe4943a
EditorCaretColor=0xf5edba

# editor syntax highlighting
SyntaxComment=0x8c8fae
SyntaxStringLiteral=0xc0c741
SyntaxCharacterLiteral=0xc0c741
SyntaxInstruction=0x7ec4c1
SyntaxAssemblerDirective=0x70377f
SyntaxRegister=0xd26471
SyntaxLabel=0xf5edba
SyntaxOperator=0xf5edba
SyntaxInvalid=0x9d303b
SyntaxMacroParameter=0x70377f

# table rows
EvenRowBackground=0xd9c8bf
EvenRowForeground=0x333333
OddRowBackground=0xfff7e4
OddRowForeground=0x333333

# panes in execute tab
TextSegmentHighlightBackground=0xe5d988
TextSegmentHighlightForeground=0x333333
TextSegmentDelaySlotHighlightBackground=0x5ac5cc
TextSegmentDelaySlotHighlightForeground=0x333333
DataSegmentHighlightBackground=0xe5d988
DataSegmentHighlightForeground=0x333333
RegisterHighlightBackground=0xe5d988
RegisterHighlightForeground=0x333333