# colours from:
# https://lospec.com/palette-list/rkbv
# https://lospec.com/palette-list/simplejpc-16
Name=PinkBlue
Splash=Colourful!

# base colours
White=0xfff5f7
Black=0x15191a
PrimaryDarkShadow=0x456b73
PrimaryShadow=0x4b97a6
Primary=0xa5bdc2
SecondaryDarkShadow=0x8a4c58
SecondaryShadow=0xd96275
Secondary=0xe6b8c1

# text editor
EditorBackground=0x050403
EditorForeground=0xfefefe
EditorLineHighlight=0x221f31
EditorSelection=0xe1b047
EditorCaretColor=0xfefefe

# editor syntax highlighting
SyntaxComment=0x9a93b7
SyntaxStringLiteral=0x7cc264
SyntaxCharacterLiteral=0x7cc264
SyntaxInstruction=0x8be1e0
SyntaxAssemblerDirective=0xa568d4
SyntaxRegister=0xea9182
SyntaxLabel=0xfefefe
SyntaxOperator=0xfefefe
SyntaxInvalid=0xa14d3f
SyntaxMacroParameter=0x9b6e2d

# table rows
EvenRowBackground=0xa5bdc2
EvenRowForeground=0x15191a
OddRowBackground=0xfff5f7
OddRowForeground=0x15191a

# panes in execute tab
TextSegmentHighlightBackground=0x8a4c58
TextSegmentHighlightForeground=0xfff5f7
TextSegmentDelaySlotHighlightBackground=0x456b73
TextSegmentDelaySlotHighlightForeground=0xfff5f7
DataSegmentHighlightBackground=0x8a4c58
DataSegmentHighlightForeground=0xfff5f7
RegisterHighlightBackground=0x8a4c58
RegisterHighlightForeground=0xfff5f7

# gradients
ButtonGradientOuter=0x4b97a6
ButtonGradientCenter=0xfff5f7
MenuGradientOuter=0xfff5f7
MenuGradientCenter=0xd96275

# misc
FocusColor=0x8a4c58
DesktopColor=0xa5bdc2
MenuBackground=0xd96275
MenuSelectedBackground=0xe6b8c1
MenuDisabledForeground=0xa5bdc2
TabbedPane.foreground=0xfff5f7
TableHeader.foreground=0x15191a
Label.foreground=0x15191a