# colours from:
# https://lospec.com/palette-list/blue-glass
# https://lospec.com/palette-list/nord-theme
Name=Sea Glass

# base colours
White=0xcbdbfc
Black=0x0c0a1b
PrimaryDarkShadow=0x6882b6
PrimaryShadow=0x83aa9c
Primary=0xa4c2cd
SecondaryDarkShadow=0x222034
SecondaryShadow=0x394c62
Secondary=0x626d83

# text editor
EditorBackground=0x3b4252
EditorForeground=0xeceff4
EditorLineHighlight=0x434c5e
EditorSelection=0x5e81ac
EditorCaretColor=0xeceff4

# editor syntax highlighting
SyntaxComment=0xd8dee9
SyntaxStringLiteral=0xa3be8c
SyntaxCharacterLiteral=0xa3be8c
SyntaxInstruction=0x88c0d0
SyntaxAssemblerDirective=0xb48ead
SyntaxRegister=0xd08770
SyntaxLabel=0xe5e9f0
SyntaxOperator=0xeceff4
SyntaxInvalid=0xbf616a
SyntaxMacroParameter=0xebcb8b

# table rows
EvenRowBackground=cbdbfc
EvenRowForeground=0x0c0a1b
OddRowBackground=0xa4c2cd
OddRowForeground=0x0c0a1b

# panes in execute tab
TextSegmentHighlightBackground=0x394c62
TextSegmentHighlightForeground=0xeceff4
TextSegmentDelaySlotHighlightBackground=0x83aa9c
TextSegmentDelaySlotHighlightForeground=0xeceff4
DataSegmentHighlightBackground=0x394c62
DataSegmentHighlightForeground=0xeceff4
RegisterHighlightBackground=0x394c62
RegisterHighlightForeground=0xeceff4

# gradients
ButtonGradientOuter=0x83aa9c
ButtonGradientCenter=0xa4c2cd
MenuGradientOuter=0xeceff4
MenuGradientCenter=0x83aa9c
SliderGradientOuter=0x394c62
SliderGradientCenter=0x6882b6

# misc
FocusColor=0x83aa9c
DesktopColor=0x394c62
TabbedPane.foreground=0xeceff4
TableHeader.foreground=0xeceff4
Table.foreground=0x0c0a1b
Label.foreground=0xeceff4
ControlTextColor=0xeceff4